### PR TITLE
Fix delete query response and delete program response

### LINKED ISSUE #62: Delete query http request always responds true
DELETE http://localhost:3000/protected/query/77Oyiqj9BcS7eqnfvFa5r0XRWO
for any string after protected/query/ always responds with

```
{
    "found": true,
    "deleted": true
}
```

### LINKED ISSUE #63: Delete program http request always responds true
DELETE http://localhost:3000/protected/program/fpnaSzYV38Y87YEhfxTBaU9Eyv
for any string after protected/program/ always responds with

```
[
    {
        "deleted": true
    },
    {
        "took": 6,
        "timed_out": false,
        "total": 0,
        "deleted": 0,
        "batches": 0,
        "version_conflicts": 0,
        "noops": 0,
        "retries": {
            "bulk": 0,
            "search": 0
        },
        "throttled_millis": 0,
        "requests_per_second": -1,
        "throttled_until_millis": 0,
        "failures": []
    }
]
```

### PR DESCRIPTION
**Pull request by CodyGramlich**
Fixes #62. Fixes #63.

When a request is sent to delete a query, it always responds with
```
{
    "found": true,
    "deleted": true
}
```
Now it will respond with
```
{
    "found": null,
    "deleted": false
}
```
when the query failed to delete.

When a request is sent to delete a program, the response is always
```
[
    {
        "deleted": true
    },
    {
        "took": 6,
        "timed_out": false,
        "total": 0,
        "deleted": 0,
        "batches": 0,
        "version_conflicts": 0,
        "noops": 0,
        "retries": {
            "bulk": 0,
            "search": 0
        },
        "throttled_millis": 0,
        "requests_per_second": -1,
        "throttled_until_millis": 0,
        "failures": []
    }
]
```

Now it will respond with
```
{
    "deleted": true,
    "queries_deleted": 5
}
```
when the program successfully deleted. The 5 indicates the number of queries that were deleted that were linked to the program. It will respond with
```
{
    "deleted": false,
    "queries_deleted": 0
}
```
when the program failed to delete.

The frontend responds accordingly with success or failure messages.

I added a few unit tests on the backend for program deletion and query deletion.

### CODE REVIEW

File: frontend/src/app/admin/programs/program-edit/program-edit.component.ts [hunk 1]
```diff
@@ -60,23 +60,20 @@ export class ProgramEditComponent implements OnInit {
...
+        if (deleteResponse) {
           this.display('delete success.')
           this.router.navigateByUrl('admin/programs/overview');
-        })
-      ).subscribe({
-        error: e => {
-          console.error(e);
-          this.display('delete failure.')
         }
+        this.display('delete failure.')
```
Comment (j-rewerts) [inline frontend/src/app/admin/programs/program-edit/program-edit.component.ts]: Add an else for this line.
